### ISSUE TITLE
PCUC - male female - in power of attorney and PCUC

### ISSUE THREAD

**Issue by Margy9** [DouwJacobs/DraftWise---Issues#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DouwJacobs** [comment]
Insert male/female as variables for PCUC. 

Also pass isPCUC and isANC as variables to word

**Comment by DouwJacobs** [comment]
Fixed in v1.2.0
